spring.application.name=summary-data

# === News API 進階設定 ===
newsapi.key=${NEWS_API_KEY}
newsapi.url=https://newsapi.org/v2/everything
newsapi.query=AI
newsapi.language=zh
newsapi.pageSize=25
newsapi.sortBy=popularity

# 排程設定：每天早上 9 點
app.cron.expression=0 0 9 * * ?

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/summary_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:9876}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.datasource.sql-script-encoding=UTF-8


logging.config=classpath:log4j2.xml